---
apiVersion: v1
kind: Secret
metadata:
  name: jboss-t5-repo
  namespace: openshift-gitops
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/janus-backstage/jboss-t5-gitops.git
